In [1]:
import h5py
import numpy as np
import pickle

filename = r'C:\Users\matti\github\DSNet\datasets\eccv16_dataset_summe_google_pool5.h5'

with h5py.File(filename, "r") as f:

	video_i = "video_1"

	print("******* DEFAULT FEATURES **********")
	original=f[video_i]["features"][:3]

	print("******* LENET FEATURES **********")
	mine=f[video_i]["seq_lenet"][:3]



******* DEFAULT FEATURES **********
******* LENET FEATURES **********


### Save

In [2]:
file = open("mine.txt", "w")
for feat in mine:
    np.savetxt(file, feat)
file.close()

In [3]:
file = open("original.txt", "w")
for feat in original:
    np.savetxt(file, feat)
file.close()

### Load

In [14]:
mine_array = np.loadtxt("mine.txt").reshape(3,1024)
print(mine_array)

[[0.04824348 0.04978595 0.00840192 ... 0.03043105 0.04858444 0.03370279]
 [0.05256166 0.05980765 0.0072507  ... 0.02120193 0.03935884 0.03196014]
 [0.05083434 0.06407385 0.01015362 ... 0.02778372 0.04081437 0.03971195]]


In [15]:
original_array = np.loadtxt("original.txt").reshape(3,1024)
print(original_array)

[[0.00000000e+00 0.00000000e+00 3.61840939e-04 ... 1.02224345e-04
  2.28259116e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.40301369e-04 ... 3.51528870e-03
  4.94062938e-02 0.00000000e+00]
 [0.00000000e+00 5.40758716e-04 2.82520137e-04 ... 4.78237853e-05
  2.36145183e-02 0.00000000e+00]]
